### ISSUE TITLE
CodeCoverage Artifacts 

### ISSUE THREAD

**Issue by tnishamon** [UNLV-CS472-672/2024-S-GROUP2-2DRove#53]
When we run coverage tests, an HTML report is generated giving us a breakdown of what was covered. 
![image](https://github.com/UNLV-CS472-672/2024-S-GROUP2-2DRove/assets/92564751/5792a2b0-8383-49b0-a5e7-91066a5e5019)

The problem with this method, is when we run the UnityTests in batch mode, there are some issues with acquiring the artifacts for the coverage report. I can work on either getting the xml file to work and output clean looking coverage percents or work on uploading the html report to an artifacts folder. 
```
name: 2DRove CI workflow

on:
  # Replace with whatever branch you're working on :)
  push: 
    branches: 
      - testtest
  pull_request:
    branches:
      - testtest

jobs:
  runTests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Checkout repo code
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      # Caches information to make future jobs go faster
      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: Library
          key: Library
      # Runs tests using integrated Test Runner for workflows
      - name: Unity - Test runner
        uses: game-ci/unity-test-runner@v4.1.1
        # Need to generate Pro Unity license with Github secrets to get this to work   
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: 2DRove
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 2022.3.19f1
          testMode: playmode
          customParameters: -debugCodeOptimization -enableCodeCoverage -coverageResultsPath ./coverage-results -coverageOptions generateHtmlReport
      # Archive our code coverage results in a zip file (will try to output it to actions later)
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: 2DRove/CodeCoverage
```
          
  Here the yaml file so far, it currently just pulls what is written to our CodeCoverage path with read and write perms on GitHub.
